export const CONSTANTS = {
  MAX_LOGIN_ATTEMPTS: 5,
  LOCKOUT_DURATION_MS: 5 * 60 * 1000,
  MAX_PHOTOS_PER_PRODUCT: 5,
  PHOTO_MAX_WIDTH: 800,
  DEFAULT_MIN_STOCK: 2,
  DEFAULT_PAGE_SIZE: 50,
  SALE_REFERENCE_PREFIX: 'VTE',
  PRODUCT_REFERENCE_PREFIX: 'PRD',
  BACKUP_INTERVAL_MS: 60 * 60 * 1000,
  
  ROLES: { ADMIN: 'ADMIN', CASHIER: 'CASHIER' },
  STATUS: { ACTIVE: 'ACTIVE', INACTIVE: 'INACTIVE' },
  CONDITIONS: { EXCELLENT: 'EXCELLENT', VERY_GOOD: 'VERY_GOOD', GOOD: 'GOOD' },
  MOVEMENT_TYPES: { IN: 'IN', OUT: 'OUT' },
  DISCOUNT_TYPES: { PERCENTAGE: 'PERCENTAGE', FIXED: 'FIXED' }
} as const;

export default CONSTANTS;
